import type { Artist } from "@/src/types";

export const mockArtists: Artist[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    bio: "Professional jazz vocalist with 10+ years experience",
    location: "New York, NY",
    city: "New York",
    categories: ["Singers"],
    languages: ["English", "French"],
    feeRange: "$500-1000",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: "Marcus Rodriguez",
    bio: "Contemporary dancer and choreographer",
    location: "Los Angeles, CA",
    city: "Los Angeles",
    categories: ["Dancers"],
    languages: ["English", "Spanish"],
    feeRange: "$300-800",
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "3",
    name: "DJ Phoenix",
    bio: "Electronic music producer and DJ specializing in house and techno",
    location: "Miami, FL",
    city: "Miami",
    categories: ["DJs"],
    languages: ["English"],
    feeRange: "$800-1500",
    createdAt: new Date("2024-01-25"),
  },
  {
    id: "4",
    name: "Dr. Amanda Chen",
    bio: "Motivational speaker and business consultant",
    location: "San Francisco, CA",
    city: "San Francisco",
    categories: ["Speakers"],
    languages: ["English", "Mandarin"],
    feeRange: "$1000-2000",
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "5",
    name: "Isabella Martinez",
    bio: "Flamenco dancer and instructor",
    location: "Austin, TX",
    city: "Austin",
    categories: ["Dancers"],
    languages: ["English", "Spanish"],
    feeRange: "$400-900",
    createdAt: new Date("2024-02-05"),
  },
  {
    id: "6",
    name: "Robert Thompson",
    bio: "Country music singer and songwriter",
    location: "Nashville, TN",
    city: "Nashville",
    categories: ["Singers"],
    languages: ["English"],
    feeRange: "$600-1200",
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "7",
    name: "DJ Luna",
    bio: "Wedding and event DJ with diverse music selection",
    location: "Chicago, IL",
    city: "Chicago",
    categories: ["DJs"],
    languages: ["English", "Polish"],
    feeRange: "$400-800",
    createdAt: new Date("2024-02-15"),
  },
  {
    id: "8",
    name: "Michael Foster",
    bio: "Tech industry keynote speaker and entrepreneur",
    location: "Seattle, WA",
    city: "Seattle",
    categories: ["Speakers"],
    languages: ["English"],
    feeRange: "$1500-3000",
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "9",
    name: "Aria Patel",
    bio: "Classical Indian vocalist and music teacher",
    location: "Houston, TX",
    city: "Houston",
    categories: ["Singers"],
    languages: ["English", "Hindi", "Gujarati"],
    feeRange: "$300-700",
    createdAt: new Date("2024-02-25"),
  },
  {
    id: "10",
    name: "Carlos Mendez",
    bio: "Salsa dance instructor and performer",
    location: "Phoenix, AZ",
    city: "Phoenix",
    categories: ["Dancers"],
    languages: ["English", "Spanish"],
    feeRange: "$350-750",
    createdAt: new Date("2024-03-01"),
  },
  {
    id: "11",
    name: "DJ Voltage",
    bio: "Hip-hop and R&B specialist for clubs and events",
    location: "Atlanta, GA",
    city: "Atlanta",
    categories: ["DJs"],
    languages: ["English"],
    feeRange: "$600-1100",
    createdAt: new Date("2024-03-05"),
  },
  {
    id: "12",
    name: "Lisa Wang",
    bio: "Leadership coach and corporate trainer",
    location: "Boston, MA",
    city: "Boston",
    categories: ["Speakers"],
    languages: ["English", "Mandarin"],
    feeRange: "$800-1600",
    createdAt: new Date("2024-03-10"),
  },
];
